"use client";

import { jsPDF } from "jspdf";
import type { CoverLetter } from "@/types/cover-letter.types";

export function exportCoverLetterToPDF(letter: CoverLetter) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxWidth = pageWidth - margin * 2;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Cover Letter", margin, margin + 5);

  // Subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(
    `${letter.jobTitle} at ${letter.companyName}`,
    margin,
    margin + 12,
  );
  doc.text(
    `Style: ${letter.style} | ${letter.wordCount} words`,
    margin,
    margin + 18,
  );

  // Divider
  doc.setDrawColor(200);
  doc.line(margin, margin + 22, pageWidth - margin, margin + 22);

  // Body — strip HTML tags
  const tempDiv = document.createElement("div");
  tempDiv.innerHTML = letter.content;
  const plainText = tempDiv.textContent || tempDiv.innerText || "";

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(30);

  const lines = doc.splitTextToSize(plainText, maxWidth);
  let y = margin + 30;

  for (const line of lines) {
    if (y > 275) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += 6;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    `Generated by JobDeck — ${new Date().toLocaleDateString()}`,
    margin,
    285,
  );

  const filename = `CoverLetter_${letter.companyName.replace(/\s+/g, "_")}_${letter.jobTitle.replace(/\s+/g, "_")}.pdf`;
  doc.save(filename);
}
